parameters:
#    loyko_max.example.class: Loyko\MaxBundle\Example

services:
#    loyko_max.example:
#        class: %loyko_max.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
